export var data = [
  {
    'id': '29941936081083614',
    'label': 'test-longlat',
    'type': 'ipc',
    'isLeaf': true,
    'deviceStatus': 'new',
    'streamStatus': '',
    'channelNum': 0,
    'multiStreamSize': 0,
    'autoStreamNum': 0,
    'deviceStreams': [],
    'inProtocol': '',
    'totalSize': 0,
    'onlineSize': 0,
    'orderSequence': '-1642665206933'
  },
  {
    'id': '29941976883272917',
    'label': '1231',
    'type': 'platform',
    'isLeaf': false,
    'deviceStatus': 'new',
    'streamStatus': '',
    'channelNum': 0,
    'multiStreamSize': 0,
    'autoStreamNum': 0,
    'deviceStreams': [],
    'inProtocol': '',
    'totalSize': 0,
    'onlineSize': 0,
    'orderSequence': '-1642492887850'
  },
  {
    'id': '29942060635135093',
    'label': '11111111',
    'type': 'nvr',
    'isLeaf': false,
    'deviceStatus': 'off',
    'streamStatus': '',
    'channelNum': 0,
    'multiStreamSize': 0,
    'autoStreamNum': 0,
    'deviceStreams': [],
    'inProtocol': '',
    'totalSize': 10,
    'onlineSize': 0,
    'orderSequence': '-1641896040125',
    'dirs': [
      {
        'id': '29942000505592950',
        'label': 'IPC',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': 'off',
        'channelNum': 1,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29942054192684151',
        'label': '大华IPC92-des从的s额12345678-0-2123203921fvrvrrsffef',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': 'off',
        'channelNum': 2,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29942150829448312',
        'label': 'HIK-ipc90',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': 'off',
        'channelNum': 3,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29941996210625657',
        'label': 'ffddCamer地方a 01sss是sf',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': 'off',
        'channelNum': 4,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29942116469709946',
        'label': '大华ipc-194',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': 'off',
        'channelNum': 5,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29942002653076603',
        'label': '通道6',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': '',
        'channelNum': 6,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29942067077586044',
        'label': '通道7',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': '',
        'channelNum': 7,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29942069225069693',
        'label': '通道8',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': '',
        'channelNum': 8,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29941957555919998',
        'label': '通道9',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': '',
        'channelNum': 9,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      },
      {
        'id': '29941914606247039',
        'label': '通道10',
        'type': 'ipc',
        'isLeaf': true,
        'deviceStatus': 'off',
        'streamStatus': '',
        'channelNum': 10,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 0,
        'onlineSize': 0,
        'orderSequence': '0'
      }
    ]
  },
  {
    'id': '326804336451174400',
    'label': 'dir2',
    'type': 'dir',
    'isLeaf': false,
    'deviceStatus': '',
    'streamStatus': '',
    'channelNum': 0,
    'multiStreamSize': 0,
    'autoStreamNum': 0,
    'deviceStreams': [],
    'inProtocol': '',
    'totalSize': 12,
    'onlineSize': 0,
    'orderSequence': '-1636973447294',
    'dirs': [
      {
        'id': '29942114322224522',
        'label': 'NVR12路',
        'type': 'nvr',
        'isLeaf': false,
        'deviceStatus': 'off',
        'streamStatus': '',
        'channelNum': 0,
        'multiStreamSize': 0,
        'autoStreamNum': 0,
        'deviceStreams': [],
        'inProtocol': '',
        'totalSize': 12,
        'onlineSize': 0,
        'orderSequence': '-1636973925305',
        'dirs': [
          {
            'id': '29942094994871697',
            'label': 'IPCamera 06',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 7,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '0'
          },
          {
            'id': '29942112174740879',
            'label': 'IPCamera 02',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 5,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '1'
          },
          {
            'id': '29941994063140240',
            'label': 'Camera 01',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 6,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '2'
          },
          {
            'id': '29942135797061010',
            'label': 'ffddCamer地方a 01sss是sf',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 8,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '3'
          },
          {
            'id': '29942172304283022',
            'label': 'IPCamera 01',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': '',
            'channelNum': 4,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '4'
          },
          {
            'id': '29942045602747795',
            'label': 'IPCamera 06',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': '',
            'channelNum': 9,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '5'
          },
          {
            'id': '29941961850885524',
            'label': '西教学楼二楼(行政室办公室)',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': '',
            'channelNum': 10,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '6'
          },
          {
            'id': '29942060635133333',
            'label': '通道11',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': '',
            'channelNum': 11,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '7'
          },
          {
            'id': '29942170156799382',
            'label': '通道12',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': '',
            'channelNum': 12,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '8'
          },
          {
            'id': '29941942523532683',
            'label': '通道名称长度测试channelName',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 1,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '9'
          },
          {
            'id': '29941921048696204',
            'label': '123_sdes从的s额12345678-0-2123203921fvrvrrsffef',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 2,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '10'
          },
          {
            'id': '29942146534479245',
            'label': 'ffddCamer地方a 01sss是sf',
            'type': 'ipc',
            'isLeaf': true,
            'deviceStatus': 'off',
            'streamStatus': 'off',
            'channelNum': 3,
            'multiStreamSize': 0,
            'autoStreamNum': 0,
            'deviceStreams': [],
            'inProtocol': '',
            'totalSize': 0,
            'onlineSize': 0,
            'orderSequence': '11'
          }
        ]
      }
    ]
  }
]